#!/usr/bin/env bash

prompt_git() {
  local branchName='';

  # Check if the current directory is in a Git repository.
  git rev-parse --is-inside-work-tree &>/dev/null || return;

  # Check for what branch we’re on.
  # Get the short symbolic ref. If HEAD isn’t a symbolic ref, get a
  # tracking remote branch or tag. Otherwise, get the
  # short SHA for the latest commit, or give up.
  branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
    git describe --all --exact-match HEAD 2> /dev/null || \
    git rev-parse --short HEAD 2> /dev/null || \
    echo 'unknown')";

  echo -e "(${branchName})";
}

# Direnv cannot self update PS1 when auto-loading python environments
# This is a work around to update the prompt appropriately
show_virtual_env() {
  if [[ -n "$VIRTUAL_ENV" && -n "$DIRENV_DIR" ]]; then
    echo "($(basename $PWD)) "
  fi
}
export PS1='$(show_virtual_env)\t \u@\h:\w$(prompt_git)\$ '

# Commenting out in favor of simpler prompt, might feel differently in
# the future
# if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
#   export TERM='gnome-256color';
# elif infocmp xterm-256color >/dev/null 2>&1; then
#   export TERM='xterm-256color';
# fi;

# if tput setaf 1 &> /dev/null; then
#   tput sgr0; # reset colors
#   bold=$(tput bold);
#   # reset=$(tput sgr0);
#   reset="\e[0m";
#   # Solarized colors, taken from http://git.io/solarized-colors.
#   black=$(tput setaf 0);
#   blue=$(tput setaf 33);
#   cyan=$(tput setaf 37);
#   green=$(tput setaf 64);
#   orange=$(tput setaf 166);
#   purple=$(tput setaf 125);
#   red=$(tput setaf 124);
#   violet=$(tput setaf 61);
#   white=$(tput setaf 15);
#   yellow=$(tput setaf 136);
# else
#   bold='';
#   reset="\e[0m";
#   black="\e[1;30m";
#   blue="\e[1;34m";
#   cyan="\e[1;36m";
#   green="\e[1;32m";
#   orange="\e[1;33m";
#   purple="\e[1;35m";
#   red="\e[1;31m";
#   violet="\e[1;35m";
#   white="\e[1;37m";
#   yellow="\e[1;33m";
# fi;

# # Highlight the user name when logged in as root.
# if [[ "${USER}" == "root" ]]; then
# 	userStyle="${red}";
# else
# 	userStyle="${orange}";
# fi;

# # Highlight the hostname when connected via SSH.
# if [[ "${SSH_TTY}" ]]; then
# 	hostStyle="${bold}${red}";
# else
# 	hostStyle="${yellow}";
# fi;

# PS1="\[${cyan}\]\t " # current time
# PS1+="\[${userStyle}\]\u" # username
# PS1+="\[${white}\]@"
# PS1+="\[${hostStyle}\]\h" # host
# PS1+="\[${white}\]:"
# PS1+="\[${green}\]\w" # working directory full path
# PS1+="\[${violet}\]\$(prompt_git)" # Git repository details
# PS1+="\[${white}\]\$ \[${reset}\]" # `$` (and reset color)
# export PS1;
