#!/usr/bin/env bash

# Make emacs the default editor
export VISUAL=emacsclient
export EDITOR=emacsclient

# Prefer US Engligh and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Go
if [ -d "$HOME/workspace/go" ]; then
  export GOPATH=$HOME/workspace/go
fi
