#!/usr/bin/env bash

# Rust
if [ -d "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi

# Setup Pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init - --path)"
  eval "$(pyenv virtualenv-init - --path)"
fi
