#!/usr/bin/env bash

# Setup Homebrew
if [ -f "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Rust
if [ -d "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi
