#!/usr/bin/env bash

# Setup Homebrew
if [ -f "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Setup Pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init - bash)"
  eval "$(pyenv virtualenv-init -)"
fi

# Rust
if [ -d "$HOME/.cargo/env" ]; then
  source "$HOME/.cargo/env"
fi
