#!/usr/bin/env bash

paths=()

# MySQL Workbench
if [ -d "/Applications/MySQLWorkbench.app/Contents/MacOS" ]; then
  paths+=("/Applications/MySQLWorkbench.app/Contents/MacOS")
fi

# Go
if [ -n "$GOPATH" ] && [ -d "$GOPATH/bin" ]; then
  paths+=("$GOPATH/bin")
fi

# Add to PATH only if not already present
for path in ${paths[*]}; do
  [[ ":$PATH:" != *":$path:"* ]] && export PATH="${path}:${PATH}"
done
